FROM node:18-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

ENV NODE_ENV=development REACT_APP_API_URL=http://localhost:5000 CHOKIDAR_USEPOLLING=true WATCHPACK_POLLING=true

EXPOSE 3000

CMD ["npm", "start"]