FROM python:3.9-slim

WORKDIR /app

RUN apt-get update && apt-get install -y gcc postgresql-client libpq-dev && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY . .

ENV FLASK_APP=app.py FLASK_ENV=development FLASK_DEBUG=1 PYTHONUNBUFFERED=1

EXPOSE 5000