# k8s-manifests/frontend/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: hiraya-frontend-config
  namespace: cet-rduran
data:
  default.conf: |
    server {
      listen 80;
      server_name _;

      include /etc/nginx/mime.types;
      root /usr/share/nginx/html;
      index index.html;

      location /static/ {
        try_files $uri $uri/ =404;
        expires 1y;
        access_log off;
        add_header Cache-Control "public";
      }

      location / {
        try_files $uri $uri/ /index.html;
        add_header Cache-Control "no-store, no-cache, must-revalidate";
      }

      location /health {
        access_log off;
        return 200 "healthy\n";
      }

      location /api/ {
        proxy_pass http://hiraya-backend:5000/;
        proxy_http_version 1.1;
        proxy_set_header Authorization $http_authorization;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      }

      gzip on;
      gzip_vary on;
      gzip_proxied any;
      gzip_comp_level 6;
      gzip_types text/plain text/css text/xml application/javascript application/json;
    }