# k8s-manifests/frontend/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hiraya-frontend
  namespace: cet-rduran
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hiraya-frontend
  template:
    metadata:
      labels:
        app: hiraya-frontend
    spec:
      containers:
      - name: hiraya-frontend
        image: amihanglobal/hiraya-frontend:7
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
        - name: nginx-temp
          mountPath: /var/cache/nginx
        - name: nginx-run
          mountPath: /var/run
        resources:
          limits:
            memory: "512Mi"
            cpu: "1000m"
          requests:
            memory: "256Mi"
            cpu: "500m"
        securityContext:
          runAsUser: 0
          runAsGroup: 0
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 30
      volumes:
      - name: nginx-conf
        configMap:
          name: hiraya-frontend-config
      - name: nginx-temp
        emptyDir: {}
      - name: nginx-run
        emptyDir: {}
      imagePullSecrets:
      - name: dockerhub-image-pull-secret