# k8s-manifests/frontend/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: hiraya-frontend
  namespace: cet-rduran
spec:
  type: NodePort
  selector:
    app: hiraya-frontend
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080