# k8s-manifests/database/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: cet-rduran
data:
  postgresql.conf: |
    max_connections = 200
    shared_buffers = 512MB
    work_mem = 32MB
    maintenance_work_mem = 128MB
    effective_cache_size = 1GB
    random_page_cost = 1.1
    synchronous_commit = off
    max_wal_size = 1GB
    min_wal_size = 80MB
    wal_buffers = 16MB
    checkpoint_completion_target = 0.9
    default_statistics_target = 500
    effective_io_concurrency = 200
    max_worker_processes = 8
    max_parallel_workers_per_gather = 4
    max_parallel_workers = 8
    max_parallel_maintenance_workers = 4
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-initdb
  namespace: cet-rduran
data:
  init.sql: |
    -- Initial PostgreSQL System Configuration
    ALTER SYSTEM SET max_connections = '200';
    ALTER SYSTEM SET shared_buffers = '512MB';
    ALTER SYSTEM SET work_mem = '32MB';
    ALTER SYSTEM SET maintenance_work_mem = '128MB';
    ALTER SYSTEM SET effective_cache_size = '1GB';

    -- Create application user and database
    CREATE USER "hiraya-admin" WITH PASSWORD '8yROXZstffbQv0xqBhZv' CREATEDB;  -- Using the password from secrets
    ALTER USER "hiraya-admin" WITH SUPERUSER;
    CREATE DATABASE "hiraya-db" WITH OWNER = "hiraya-admin";
    GRANT ALL PRIVILEGES ON DATABASE "hiraya-db" TO "hiraya-admin";

    -- Connect to the application database
    \c hiraya-db

    -- Set up database extensions and permissions
    CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO "hiraya-admin";
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO "hiraya-admin";