apiVersion: apps/v1
kind: Deployment
metadata:
  name: hiraya-frontend
  namespace: cet-rduran
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hiraya-frontend
  template:
    metadata:
      labels:
        app: hiraya-frontend
    spec:
      containers:
      - name: hiraya-frontend
        image: amihanglobal/hiraya_application:frontend_prod
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
        - name: nginx-temp
          mountPath: /var/cache/nginx
        - name: nginx-run
          mountPath: /var/run
        resources:
          limits:
            memory: "512Mi"
            cpu: "1000m"
          requests:
            memory: "256Mi"
            cpu: "500m"
        securityContext:
          runAsUser: 0
          runAsGroup: 0
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 30
      volumes:
      - name: nginx-conf
        configMap:
          name: hiraya-frontend-config
      - name: nginx-temp
        emptyDir: {}
      - name: nginx-run
        emptyDir: {}
      imagePullSecrets:
      - name: dockerhub-image-pull-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hiraya-backend
  namespace: cet-rduran
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hiraya-backend
  template:
    metadata:
      labels:
        app: hiraya-backend
    spec:
      initContainers:
      - name: wait-for-db
        image: postgres:14-alpine
        command: ['sh', '-c',
          'until pg_isready -h hiraya-database -p 5432 -U hiraya-admin -d hiraya-db; do echo waiting for database; sleep 2; done;']
        env:
          - name: PGPASSWORD
            value: "password"
        resources:
          limits:
            memory: "256Mi"
            cpu: "200m"
          requests:
            memory: "128Mi"
            cpu: "100m"
      containers:
      - name: hiraya-backend
        image: amihanglobal/hiraya_application:backend_prod
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /api/health
            port: 5000
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /api/health
            port: 5000
            scheme: HTTP
          initialDelaySeconds: 45
          periodSeconds: 15
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        command: ["/app/scripts/init-backend.sh"]
        env:
        - name: FLASK_APP
          valueFrom:
            configMapKeyRef:
              key: FLASK_APP
              name: hiraya-backend-config
        - name: FLASK_ENV
          valueFrom:
            configMapKeyRef:
              key: FLASK_ENV
              name: hiraya-backend-config
        - name: DB_USER
          value: "hiraya-admin"
        - name: DB_PASSWORD
          value: "password"
        - name: DB_NAME
          value: "hiraya-db"
        - name: DB_HOST
          value: "hiraya-database"
        - name: DB_PORT
          value: "5432"
        - name: DATABASE_URL
          value: "postgresql://hiraya-admin:password@hiraya-database:5432/hiraya-db"
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: CORS_ORIGINS
          valueFrom:
            configMapKeyRef:
              key: CORS_ORIGINS
              name: hiraya-backend-config
        - name: API_URL
          valueFrom:
            configMapKeyRef:
              key: API_URL
              name: hiraya-backend-config
        - name: FRONTEND_URL
          valueFrom:
            configMapKeyRef:
              key: FRONTEND_URL
              name: hiraya-backend-config
        - name: GITHUB_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: github-oauth-secret
              key: GITHUB_CLIENT_ID
        - name: GITHUB_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: github-oauth-secret
              key: GITHUB_CLIENT_SECRET
        - name: DEBUG
          value: "False"
        - name: SQLALCHEMY_POOL_SIZE
          value: "30"
        - name: SQLALCHEMY_MAX_OVERFLOW
          value: "10"
        - name: SQLALCHEMY_POOL_TIMEOUT
          value: "60"
        - name: SQLALCHEMY_POOL_RECYCLE
          value: "1800"
        - name: GUNICORN_WORKERS
          value: "4"
        - name: GUNICORN_THREADS
          value: "4"
        - name: GUNICORN_TIMEOUT
          value: "300"
        - name: GUNICORN_KEEPALIVE
          value: "5"
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: hiraya-backend-secret
              key: JWT_SECRET_KEY
        resources:
          limits:
            memory: "3Gi"
            cpu: "1500m"
          requests:
            memory: "1Gi"
            cpu: "500m"
        ports:
        - containerPort: 5000
          protocol: TCP
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          allowPrivilegeEscalation: false
      imagePullSecrets:
      - name: dockerhub-image-pull-secret