apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: argocd
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJhbWloYW5nbG9iYWwiLCJwYXNzd29yZCI6IkFtMWhAbjA4MDgifX19