# secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: hiraya-database-secret
  namespace: cet-rduran
type: Opaque
data:
  DB_USER: aGlyYXlhLWFkbWlu
  DB_PASSWORD: cGFzc3dvcmQ=
  DB_NAME: aGlyYXlhLWRi
---
apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-image-pull-secret
  namespace: cet-rduran
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJhbWloYW5nbG9iYWwiLCJwYXNzd29yZCI6IkFtMWhAbjA4MDgifX19