# secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: hiraya-database-secret
  namespace: cet-rduran
type: Opaque
data:
  DB_USER: aGlyYXlhLWFkbWlu
  DB_PASSWORD: cGFzc3dvcmQ=
  DB_NAME: aGlyYXlhLWRi
---
apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-image-pull-secret
  namespace: cet-rduran
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJhbWloYW5nbG9iYWwiLCJwYXNzd29yZCI6IkFtMWhAbjA4MDgifX19
---
apiVersion: v1
kind: Secret
metadata:
  name: hiraya-backend-secret
  namespace: cet-rduran
type: Opaque
data:
  JWT_SECRET_KEY: TWItNnJMN3BuVHZMWHE5QmhIZGxveC1sQjV5NGxDeFYxb0RKVHJJUUxWVFR0RkdmX2hUc29HM0FWV3VUTXk5VWtYYmYweW5UblUwTG9nRnlrT19VNmc=
---
apiVersion: v1
kind: Secret
metadata:
  name: github-oauth-secret
  namespace: cet-rduran
type: Opaque
data:
  GITHUB_CLIENT_ID: T3YyM2xpNk1KOHNRMGpRa2JDY1Y=
  GITHUB_CLIENT_SECRET: ZjRiMWMwMTNjNWZlY2UzMzdmMGVjNzFhMDMxMjg1YTlmNmZkMjMxNg==
---
apiVersion: v1
kind: Secret
metadata:
  name: google-oauth-secret
  namespace: cet-rduran
type: Opaque
data:
  GOOGLE_CLIENT_ID: MTk2MDQxOTM0NDY0LXFkOXIyOWJyb3Rxb2dvZHAyYXQwZDdscTgxbWFpMmo3LmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29t
  GOOGLE_CLIENT_SECRET: R09DU1BYLUExSWRRbEJnV21BNkVDSnliZ0FuQ3BleHZ2TXk=